name: bb_mobile
description: Bull Bitcoin Mobile Wallet
publish_to: "none"
version: 6.3.3+123


environment:
  sdk: ">=3.7.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  bdk_flutter:
    git:
      url: https://github.com/SatoshiPortal/bdk-flutter
      ref: c5fb2ed396a632215959efdfb2473b69d911127f
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.6
  freezed: ^3.0.0
  get_it: ^7.2.0
  extra_alignments: ^1.0.0+1
  flutter_animate: ^4.1.0
  gap: ^3.0.1
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.0.15
  payjoin_flutter:
    git:
      url: https://github.com/SatoshiPortal/payjoin-flutter
      ref: outdated-branch-with-android-patch
  qr_flutter: ^4.1.0
  dio: ^5.2.1+1
  timeago: ^3.3.0
  flutter_native_splash: ^2.4.0
  url_launcher: ^6.1.10
  file_picker: ^10.3.3
  bitcoin_utils:
    git:
      url: https://github.com/LtbLightning/bitcoin-utils-flutter
      ref: afbcbfae4addb833f46bf8b3c3899085e66941e0
  flutter_dotenv: ^5.2.1
  hex: ^0.2.0
  auto_size_text: ^3.0.0
  no_screenshot: ^0.3.1
  freezed_annotation: ^3.0.0
  convert: ^3.1.2
  crypto: ^3.0.6
  rxdart: ^0.28.0
  synchronized: ^3.3.0+3
  decimal: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  boltz:
    git:
      url: https://github.com/SatoshiPortal/boltz-dart
      ref: 187237ae477b09964f8580e24d7155c4e70254e4
  lwk:
    git:
      url: https://github.com/SatoshiPortal/lwk-dart
      ref: bc2086ab9aaf642890249f2740afa5b2c7fdc901
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: any
  bip85_entropy: ^1.0.2
  bip21_uri: ^2.1.3
  bip32_keys: ^3.0.1
  bip39_mnemonic: ^4.0.0
  bip329_labels: ^1.0.1
  bs58check: ^1.0.2
  gif: ^2.3.0
  custom_sliding_segmented_control: ^1.8.5
  shimmer: ^3.0.0
  googleapis: ^13.2.0
  google_sign_in: ^6.2.2
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  recoverbull:
    git:
      url: https://github.com/SatoshiPortal/recoverbull-client-dart.git
      ref: 9fd986d652a9c92492300249a46bf34b74043a65
  flutter_zxing: ^2.1.0
  webview_cookie_manager:
    git:
      url: https://github.com/fryette/webview_cookie_manager.git
      ref: e03954491a6952e04d7fceeae4c4d074392c0fe2
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.4
  webview_flutter_wkwebview: ^3.18.5
  async: ^2.11.0
  drift: "^2.26.1"
  drift_flutter: ^0.2.4
  package_info_plus: ^8.3.0
  share_plus: ^11.0.0
  font_awesome_flutter: ^10.8.0
  bolt11_decoder: ^1.0.2
  dart_bbqr:
    git:
      url: https://github.com/SatoshiPortal/bbqr-dart
      ref: e587b1882d4345050507357d795d26a48a160226
  sliver_tools: ^0.2.12
  logging_colorful: ^1.3.0
  timelines_plus: ^1.0.7
  satoshifier:
    git:
      url: https://github.com/SatoshiPortal/dart-satoshifier
      ref: 31cda2ef3df055fac8a74f2b7f42fc683ae44214
  flutter_nfc_kit: ^3.6.0
  ledger_bitcoin:
    git:
      url: https://github.com/SatoshiPortal/ledger-flutter-plus-plugins
      path: packages/ledger-bitcoin
      ref: c4240d1f518c5903b67191253212754a31ed5333
  permission_handler: ^12.0.1
  cbor: ^6.3.7
  ur:
    git:
      url: https://github.com/bukata-sa/bc-ur-dart.git
      ref: 5738f70d0ec3d50977ac3dd01fed62939600238b
  bitcoin_base: ^6.9.0
  ark_wallet:
    git:
      url: https://github.com/SatoshiPortal/dart-ark-wallet
      ref: 6d804430eaea8415de601356c580974d018072f6
  socks5_proxy: ^2.1.1
  tor:
    git:
      url: https://github.com/Foundation-Devices/tor
      ref: 440a2d2  

dev_dependencies:
  build_runner: ^2.4.15
  lint: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  test: ^1.25.8
  flutter_gen_runner: any
  drift_dev: ^2.26.1

flutter:
  generate: true # Needed for code generation, for example for internationalization
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/logos/
    - assets/backgrounds/
    - assets/animations/
    - assets/misc/

flutter_native_splash:
  background_image: "assets/logos/bb-logo-white-splash.png"
  android_12:
    color: "#C50909"
    image: assets/logos/bb-logo-white-splash.png
    # icon_background_color: "#C50909"
    icon_background_color: "#C50909"

  color_android: "#C50909"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/misc/iconnew.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FBFBFB"
  adaptive_icon_foreground: "assets/misc/iconnew-red.png"
