name: bb_mobile
description: Bull Bitcoin Mobile Wallet
publish_to: 'none' 
version: 0.1.99

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bdk_flutter: 0.30.0
      # ^0.28.3
      # path: ../bdk-flutter
      # git:
      #   url: https://github.com/LtbLightning/bdk-flutter.git
      #   # ref: v0.28.3

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  freezed: ^2.4.5
  get_it: ^7.2.0
  extra_alignments: ^1.0.0+1
  flextras: ^1.0.0
  flutter_animate: ^4.1.0
  gap: ^3.0.1
  go_router: ^13.2.2
  google_fonts: 6.1.0
  flutter_secure_storage: ^9.0.0

      
  json_annotation: ^4.7.0
  flutter_hooks: ^0.20.3
  flutter_barcode_scanner: ^2.0.0
  # file_picker: ^5.2.3
  # nfc_manager: ^3.2.0
  modal_bottom_sheet: ^3.0.0-pre
  font_awesome_flutter: ^10.3.0
  path_provider: ^2.0.15
  carousel_slider: ^4.2.1
  qr_flutter: ^4.1.0
  flutter_translate: ^4.0.3
  # flutter_localizations:
    # sdk: flutter
  dio: ^5.2.1+1
  timeago: ^3.3.0
  pattern_formatter: ^3.0.0
  flutter_native_splash: ^2.2.17
  url_launcher: ^6.1.10
  file_picker: ^6.1.1
  loading_animation_widget: ^1.2.0+4
  bitcoin_utils: ^0.0.1
  # permission_handler: ^11.0.1
  # widgetbook: ^3.0.0-beta.14
  # widgetbook_annotation: ^3.0.0-beta.7
  flutter_dotenv: ^5.1.0
  # uni_links: ^0.5.1
  document_file_save_plus: ^2.0.0
  hive: ^2.2.3
  flutter_file_dialog: ^3.0.1
  currency_text_input_formatter: ^2.1.10
  intl: ^0.18.1
  hex: ^0.2.0
  bloc_concurrency: ^0.2.5
  # flutter_zxing: ^1.4.1
  flutter_keyboard_visibility: ^6.0.0
  # currency_text_input_formatter: ^2.1.10
  pointycastle: ^3.1.3
  auto_size_text: ^3.0.0
  no_screenshot: ^0.0.1+6
  boltz_dart: 
    git:
      url: https://github.com/SatoshiPortal/boltz-dart.git
      ref: trunk
  flutter_svg: ^2.0.10+1
  lwk_dart: 
    git:
      url: https://github.com/SatoshiPortal/lwk-dart
      ref: trunk
      
  
  
dev_dependencies:
  build_runner: ^2.4.9
  # flutter_lints: ^2.0.1
  lint: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.5.4
  bloc_test: ^9.1.7
  mocktail: ^1.0.1
  # flutter_launcher_icons: 

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/textlogo.png
    - assets/nfc_scan.png
    - assets/cc-logo.png
    - assets/bb-logo2.png
    - assets/bb-white.png
    - assets/arrow_down.png
    - assets/arrow_down_white.png
    - assets/request-payment.svg
    - assets/new-address.svg
    
    - assets/bip39_english.txt

flutter_native_splash:
  background_image: "assets/splash.png"
  android_12:
    color: "#C50909"
    image: assets/iconlarge.png
    # icon_background_color: "#C50909"
    icon_background_color: "#000000"

  color_android: "#C50909"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
