name: bb_mobile
description: Bull Bitcoin Mobile Wallet
publish_to: "none"
version: 0.5.6+43

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bdk_flutter:
    git:
      url: https://github.com/LtbLightning/bdk-flutter
      ref: ac8d102240a4242e319e71492d3698828177e97b
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.6
  freezed: ^3.0.0
  get_it: ^7.2.0
  extra_alignments: ^1.0.0+1
  flextras: ^1.0.0
  flutter_animate: ^4.1.0
  gap: ^3.0.1
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.1.0
  flutter_hooks: ^0.20.3
  # flutter_barcode_scanner: ^2.0.0
  # file_picker: ^5.2.3
  # nfc_manager: ^3.2.0
  modal_bottom_sheet: ^3.0.0-pre
  font_awesome_flutter: ^10.3.0
  path_provider: ^2.0.15
  payjoin_flutter:
    git:
      url: https://github.com/LtbLightning/payjoin-flutter
      ref: release/v0.23.0-dev.1
  carousel_slider: ^4.2.1
  qr_flutter: ^4.1.0
  flutter_translate: ^4.0.3
  dio: ^5.2.1+1
  timeago: ^3.3.0
  flutter_native_splash: ^2.4.0
  url_launcher: ^6.1.10
  file_picker: ^8.0.3
  loading_animation_widget: ^1.2.0+4
  bitcoin_utils:
    git:
      url: https://github.com/LtbLightning/bitcoin-utils-flutter
      ref: afbcbfae4addb833f46bf8b3c3899085e66941e0
  # permission_handler: ^11.0.1
  # widgetbook: ^3.0.0-beta.14
  # widgetbook_annotation: ^3.0.0-beta.7
  flutter_dotenv: ^5.2.1
  # uni_links: ^0.5.1
  document_file_save_plus: ^2.0.0
  flutter_file_dialog: ^3.0.1
  currency_text_input_formatter: ^2.1.10
  hex: ^0.2.0
  bloc_concurrency: ^0.2.5
  # flutter_zxing: ^1.4.1
  flutter_keyboard_visibility: ^6.0.0
  # currency_text_input_formatter: ^2.1.10
  pointycastle: ^3.7.3
  auto_size_text: ^3.0.0
  no_screenshot: ^0.3.1
  flutter_svg: ^2.0.10+1
  oktoast: ^3.4.0
  lottie: ^3.1.0
  freezed_annotation: ^3.0.0
  convert: ^3.1.2
  crypto: ^3.0.6
  permission_handler: ^11.3.1
  rxdart: ^0.28.0
  synchronized: ^3.3.0+3
  decimal: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  boltz: ^0.2.0
  lwk: ^0.2.0
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: any
  bip32: ^2.0.0
  bip39_mnemonic: ^3.0.9
  bs58check: ^1.0.2
  auto_size_text_field: ^2.2.4
  gif: ^2.3.0
  custom_sliding_segmented_control: ^1.8.5
  animated_svg: ^2.1.0
  shimmer: ^3.0.0
  dart_bip21: ^1.0.0
  googleapis: ^13.2.0
  google_sign_in: ^6.2.2
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  recoverbull:
    git:
      url: https://github.com/SatoshiPortal/recoverbull-client-dart.git
      ref: 334b5402d8b7b80b4736663861f7952020312831
  bip85: ^2.0.0
  camera: ^0.11.1
  zxing2: ^0.2.3
  webview_cookie_manager:
    git:
      url: https://github.com/fryette/webview_cookie_manager.git
      ref: e03954491a6952e04d7fceeae4c4d074392c0fe2
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.4
  webview_flutter_wkwebview: ^3.18.5
  async: ^2.11.0
  drift: "^2.26.1"
  drift_flutter: ^0.2.4
  package_info_plus: ^8.3.0
  share_plus: ^11.0.0

dev_dependencies:
  build_runner: ^2.4.15
  # flutter_lints: ^2.0.1
  lint: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.1
  bloc_test: ^9.1.7
  mocktail: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  test: ^1.25.8
  # fluttergen: ^5.9.0
  flutter_gen_runner: any
  drift_dev: ^2.26.1

#dependency_overrides:
#  analyzer: ^6.4.1
#  build_resolvers: ^2.3.5
#  dart_style: ^2.3.6

#dependency_overrides:
#  analyzer: ^6.4.1
#  build_resolvers: ^2.3.5
#  dart_style: ^2.3.6

flutter:
  generate: true # Needed for code generation, for example for internationalization
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/
    - assets/icons/
    - assets/images2/
    # - assets/textlogo.png
    # - assets/nfc_scan.png
    # - assets/cc-logo.png
    # - assets/bb-logo2.png
    # - assets/bb-white.png
    # - assets/arrow_down.png
    # - assets/arrow_down_white.png
    # - assets/request-payment.svg
    # - assets/new-address.svg

    - assets/bip39_english.txt

flutter_native_splash:
  background_image: "assets/splash.png"
  android_12:
    color: "#C50909"
    image: assets/bb-logo-white-splash.png
    # icon_background_color: "#C50909"
    icon_background_color: "#C50909"

  color_android: "#C50909"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/iconnew.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FBFBFB"
  adaptive_icon_foreground: "assets/iconnew-red.png"
