name: bb_mobile
description: Bull Bitcoin Mobile Wallet
publish_to: "none"
version: 6.4.0+131


environment:
  sdk: ">=3.10.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  bdk_flutter:
    git:
      url: https://github.com/SatoshiPortal/bdk-flutter
      ref: frb-2.11.1
  flutter_bloc: ^9.1.1
  freezed: ^3.2.3
  get_it: ^9.1.1
  flutter_animate: ^4.5.2
  gap: ^3.0.1
  go_router: ^17.0.0
  google_fonts: ^6.3.3
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  payjoin_flutter:
    git:
      url: https://github.com/SatoshiPortal/payjoin-flutter
      ref: frb-2.11.1
  qr_flutter: ^4.1.0
  dio: ^5.9.0
  timeago: ^3.7.1
  flutter_native_splash: ^2.4.7
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  file_picker: 10.3.6
  bitbox_flutter:
    git:
      url: https://github.com/SatoshiPortal/bitbox-dart
      ref: frb-2.11.1
  flutter_dotenv: ^6.0.0
  hex: ^0.2.0
  auto_size_text: ^3.0.0
  no_screenshot: ^0.3.1
  freezed_annotation: ^3.1.0
  convert: ^3.1.2
  crypto: ^3.0.7
  synchronized: ^3.4.0
  decimal: ^3.2.4
  hive: ^2.2.3
  boltz:
    git:
      url: https://github.com/SatoshiPortal/boltz-dart
      ref: frb-2.11.1
  lwk:
    git:
      url: https://github.com/SatoshiPortal/lwk-dart
      ref: 2e10deb2fbaa76e888bda7be6a2128ce2c05173d
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: any
  bip85_entropy: ^1.0.2
  bip21_uri: ^2.1.3
  bip32_keys: ^3.1.1
  bip39_mnemonic: ^4.0.1
  bip329_labels: ^1.0.1
  bs58check: ^1.0.2
  gif: ^2.3.0
  custom_sliding_segmented_control: ^1.8.5
  shimmer: ^3.0.0
  googleapis: ^15.0.0
  google_sign_in: ^7.2.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  recoverbull:
    git:
      url: https://github.com/SatoshiPortal/recoverbull-client-dart.git
      ref: 9fd986d652a9c92492300249a46bf34b74043a65
  flutter_zxing: ^2.2.1
  webview_cookie_manager:
    git:
      url: https://github.com/fryette/webview_cookie_manager.git
      ref: e03954491a6952e04d7fceeae4c4d074392c0fe2
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.10
  webview_flutter_wkwebview: ^3.23.4
  async: ^2.11.0
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  package_info_plus: ^9.0.0
  share_plus: ^12.0.1
  font_awesome_flutter: ^10.12.0
  bolt11_decoder:
    git:
      url: https://github.com/fusion44/dart_bolt11_decoder
      ref: f5deec21fb0ac2ee507de1f683344b03f8cc92a3
  dart_bbqr:
    git:
      url: https://github.com/SatoshiPortal/bbqr-dart
      ref: frb-2.11.1
  sliver_tools: ^0.2.12
  logging_colorful: ^1.3.2
  satoshifier:
    git:
      url: https://github.com/SatoshiPortal/satoshifier-dart
      ref: 7b5341a5f6d8368173154132871d1f5f394019f9
  flutter_nfc_kit: ^3.6.1
  ledger_bitcoin:
    git:
      url: https://github.com/SatoshiPortal/ledger-flutter-plus-plugins
      path: packages/ledger-bitcoin
      ref: c4240d1f518c5903b67191253212754a31ed5333
  permission_handler: ^12.0.1
  cbor: ^6.3.7
  ur:
    git:
      url: https://github.com/bukata-sa/bc-ur-dart.git
      ref: 5738f70d0ec3d50977ac3dd01fed62939600238b
  bitcoin_base: ^7.0.0
  ark_wallet:
    git:
      url: https://github.com/SatoshiPortal/ark-wallet-dart
      ref: frb-2.11.1
  socks5_proxy: ^2.1.1
  tor:
    git:
      url: https://github.com/Foundation-Devices/tor
      ref: b92e2bc  
  meta: ^1.17.0
  workmanager: ^0.9.0
  path: ^1.9.1
  http: ^1.6.0
  lints: ^6.0.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.11.2
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.4
  test: ^1.26.3 
  flutter_gen_runner: any
  drift_dev: ^2.29.0

flutter:
  generate: true # Needed for code generation, for example for internationalization
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/logos/
    - assets/backgrounds/
    - assets/animations/
    - assets/misc/

flutter_native_splash:
  background_image: "assets/logos/bb-logo-white-splash.png"
  android_12:
    color: "#C50909"
    image: assets/logos/bb-logo-white-splash.png
    # icon_background_color: "#C50909"
    icon_background_color: "#C50909"

  color_android: "#C50909"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/icon-black-red.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "assets/logos/icon-black-red.png"
  adaptive_icon_foreground: "assets/logos/icon-black-red.png"
